# .github/discussion_category_templates.yml
- name: 🚀 Suggerer un Logiciel à Tester
  description: Proposez un outil ou un logiciel que je devrais tester sur la chaîne !
  is_answerable: false
  body: |
    Salut ! 👋

    Envie de voir un logiciel testé sur ma chaîne YouTube ? Super ! Pour m'aider à bien comprendre ta suggestion, réponds simplement à ces quelques questions :

    ### 📝 C'est quoi le nom du logiciel ?
    [Nom complet de l'outil ou du logiciel.]

    ### 🔗 Où le trouver ?
    [Lien vers le site officiel, GitHub, ou autre page pertinente.]

    ### 💡 Pourquoi tu penses que c'est intéressant pour la chaîne ?
    [Qu'est-ce qui rend ce logiciel unique ou pertinent pour mon audience ?]

    ### 🛠️ Pour quel usage ?
    [Décris brièvement à quoi il sert ou comment tu l'utilises.]

    ---

    **C'est tout ! Merci pour ta contribution !**
    J'examinerai toutes les suggestions, mais je ne peux pas garantir de tester chaque logiciel proposé.
